# Generated by Django 3.0.7 on 2020-06-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Бизнес - решение', 'verbose_name_plural': 'Бизнес - решения'},
        ),
    ]
