# Generated by Django 3.0.7 on 2020-06-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_auto_20200620_1721'),
        ('solutions', '0002_auto_20200620_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='idea',
            field=models.ForeignKey(blank=True, help_text='Если решение привязано к идее то это решение к идее. Если нет это предложение бизнес-решения.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.IdeaOffer', verbose_name='Идея'),
        ),
    ]
