version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./var/postgresql-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gpb_postgres
      POSTGRES_USER: gpb_postgres
      POSTGRES_PASSWORD: gpb_postgres
