# Generated by Django 3.0.7 on 2020-06-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_tree', '0001_initial'),
        ('eauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department_tree.DepartmentTree', verbose_name='Отдел'),
        ),
    ]
