# Generated by Django 3.0.7 on 2020-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_tree', '0001_initial'),
        ('eauth', '0002_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(null=True, to='department_tree.DepartmentTree', verbose_name='Отдел'),
        ),
    ]
