# Generated by Django 3.0.7 on 2020-06-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eauth', '0003_auto_20200620_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_department_head',
        ),
    ]
