# Generated by Django 3.0.7 on 2020-06-19 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_tree', '0002_auto_20200620_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttree',
            name='department_heads',
            field=models.ManyToManyField(related_name='department_heads', to=settings.AUTH_USER_MODEL, verbose_name='Главы отдела'),
        ),
        migrations.AlterField(
            model_name='departmenttree',
            name='users',
            field=models.ManyToManyField(related_name='department_users', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
