# Generated by Django 3.0.7 on 2020-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaoffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Опубликовано'), (1, 'Модерация'), (2, 'Не прошло модуляцию')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ideaoffer',
            name='tags',
            field=models.ManyToManyField(to='ideas.Tag', verbose_name='Тэги'),
        ),
    ]
