# Generated by Django 3.0.7 on 2020-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20200620_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaoffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Опубликовано'), (1, 'Модерация'), (2, 'Не прошло модерацию')], default=1, verbose_name='Статус'),
        ),
    ]
