# Generated by Django 3.0.7 on 2020-06-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20200620_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideacomment',
            options={'verbose_name': 'Комментарий к идее', 'verbose_name_plural': 'Комментарии к идее'},
        ),
        migrations.AlterModelOptions(
            name='idealike',
            options={'verbose_name': 'Лайк к идее', 'verbose_name_plural': 'Лайки к идее'},
        ),
        migrations.AlterModelOptions(
            name='ideaoffer',
            options={'verbose_name': 'Идея', 'verbose_name_plural': 'Идеи'},
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='idealike',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='idealike',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='ideaoffer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='ideaoffer',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='theme',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='theme',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='ideaoffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Опубликовано'), (1, 'Модерация'), (2, 'Не прошло модерацию'), (3, 'Решено/закрыто')], default=1, verbose_name='Статус'),
        ),
    ]
