# Generated by Django 3.0.7 on 2020-06-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20200620_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
