# Generated by Django 3.0.7 on 2020-06-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20200620_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideaoffer',
            name='themes',
        ),
        migrations.AddField(
            model_name='ideaoffer',
            name='themes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Theme', verbose_name='Темы'),
        ),
    ]
