# Generated by Django 3.0.7 on 2020-06-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20200620_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaoffer',
            name='themes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Theme', verbose_name='Выбранная тема'),
        ),
    ]
